name: Docker Image CI1

on:
  push:
    branches: [ master ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/thiagosilva977/webscraping-docker-template:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_PAT }}
          
      - name: Write digest
        run: |
          echo "${{ steps.docker_build.outputs.digest }}"
